version: '3'
services:
  db:
    build: ./mysql
    restart: always

  web:
    image: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./target/movies-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/movies.war
    depends_on:
      - db


